--EXP NO:11
--Write a database trigger that prevents changes to emp table from 5pm to 12am(statement level trigge



CREATE TABLE EMPLOYEE (
CODE VARCHAR(10),
NAME CHAR(25),
DOB DATE NOT NULL,
DESIGNATION CHAR(30),
SALARY INT
);
INSERT INTO EMPLOYEE VALUES ('C101','John','1989-06-12','CLERK','15000');
INSERT INTO EMPLOYEE VALUES ('C102','arjun','1990-12-07','TEAM LEAD','35000');
INSERT INTO EMPLOYEE VALUES ('C103','rohan','1995-02-12','MANAGER','50000');
INSERT INTO EMPLOYEE VALUES ('C104','Amal','1998-02-11','CLERK','15000');
INSERT INTO EMPLOYEE VALUES ('C105','steve','1983-07-20','SYSTEM ANALYST','25000');

DELIMITER $$
CREATE TRIGGER INSERT_PREVENT
BEFORE INSERT
ON EMPLOYEE FOR EACH ROW
BEGIN
IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER UPDATE_PREVENT
BEFORE UPDATE
ON EMPLOYEE FOR EACH ROW
BEGIN
IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER DELETE_PREVENT
BEFORE DELETE
ON EMPLOYEE FOR EACH ROW
BEGIN
IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'EMPLOYEE TABLE HAS NO CHANGES';
END IF;
END $$
DELIMITER ;
